
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUMERO SUM RES MUL DIV APAREN CPARENexp : exp SUM termexp : exp RES termexp : termterm : term MUL factorterm : term DIV factorterm : factorfactor : NUMEROfactor : APAREN exp CPAREN'
    
_lr_action_items = {'SUM':([1,3,4,5,6,11,12,13,14,15,],[-6,-3,-7,9,9,-8,-4,-5,-1,-2,]),'$end':([1,3,4,5,11,12,13,14,15,],[-6,-3,-7,0,-8,-4,-5,-1,-2,]),'RES':([1,3,4,5,6,11,12,13,14,15,],[-6,-3,-7,10,10,-8,-4,-5,-1,-2,]),'APAREN':([0,2,7,8,9,10,],[2,2,2,2,2,2,]),'MUL':([1,3,4,11,12,13,14,15,],[-6,7,-7,-8,-4,-5,7,7,]),'CPAREN':([1,3,4,6,11,12,13,14,15,],[-6,-3,-7,11,-8,-4,-5,-1,-2,]),'NUMERO':([0,2,7,8,9,10,],[4,4,4,4,4,4,]),'DIV':([1,3,4,11,12,13,14,15,],[-6,8,-7,-8,-4,-5,8,8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,2,9,10,],[3,3,14,15,]),'factor':([0,2,7,8,9,10,],[1,1,12,13,1,1,]),'exp':([0,2,],[5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp SUM term','exp',3,'p_expresion_suma','CalcParser.py',23),
  ('exp -> exp RES term','exp',3,'p_expresion_resta','CalcParser.py',28),
  ('exp -> term','exp',1,'p_exp_term','CalcParser.py',32),
  ('term -> term MUL factor','term',3,'p_term_times','CalcParser.py',36),
  ('term -> term DIV factor','term',3,'p_term_div','CalcParser.py',41),
  ('term -> factor','term',1,'p_term_factor','CalcParser.py',45),
  ('factor -> NUMERO','factor',1,'p_factor_num','CalcParser.py',49),
  ('factor -> APAREN exp CPAREN','factor',3,'p_factor_exp','CalcParser.py',53),
]
